import os,sys,time
jh=input("Magzimu 1.24T By BlackUnix.Easy Shell.Which terminal you running. 1.Terminal(Linux/Debian Base(apt only)) 2.Termux(Android) . (1/2): ")
if jh=="1":
	os.system("cd ~")
	os.system("sudo apt install git")
	os.system("git clone https://github.com/black-unix/magzimu.git")
	os.system("sudo apt update")
	os.system("sudo apt upgrade")
	os.system("sudo apt install python")
	os.system("sudo apt install python2")
	os.system("sudo apt install pip")
	os.system("sudo pip install slowloris")
	os.system("sudo apt install darkstat")
	os.system("sudo pip install requests")
	print("all Requirements installed. now do \tcd magzimu \nthen\tpython3 magzimu.py")
elif jh=="2":
	os.system("cd ~")
	os.system("apt install git")
	os.system("git clone https://github.com/black-unix/magzimu.git")
	os.system("apt update")
	os.system("apt upgrade")
	os.system("apt install python")
	os.system("apt install python2")
	os.system("apt install pip")
	os.system("pip install slowloris")
	os.system("apt install darkstat")
	os.system("pip install requests")
	print("all Requirements installed. now do \tcd magzimu \nthen\tpython3 magzimu.py")
else:
	print("next time see what choices you can choose :|")